# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookserver
  template:
    metadata:
      labels:
        app: bookserver
    spec:
      containers:
        - name: bookserver
          image: bonusree/bookserver
          ports:
            - containerPort: 8080
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: bookserver-service
spec:
  selector:
    app: bookserver
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
