apiVersion: v1
kind: Pod
metadata:
  name: nodelabels
  labels:
    env: development
spec:
  containers:
    - name: c00
      image: akiselevych/bookserver

  nodeSelector:
    harware: t2-medium  #there is no node by such name , so ready : 0/1 will show)































